In [1]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
import torch
import numpy as np
os.environ['TORCH'] = torch.__version__
os.environ['DGLBACKEND'] = "pytorch"
import dgl
import dgl.graphbolt as gb
# Install the CPU version.
device = torch.device("cpu")

OnDiskDataset for Homogeneous Graph

In [2]:
base_dir = '../../../data/dgl/ondisk_dataset_homograph'
os.makedirs(base_dir, exist_ok=True)
print(f"Created base directory: {base_dir}")

Created base directory: ../../../data/dgl/ondisk_dataset_homograph


Generate graph structure data

In [8]:
import numpy as np
import pandas as pd
num_nodes = 1000
num_edges =10*num_nodes 
edges_path = os.path.join(base_dir,"edges.csv")
edges = np.random.randint(0, num_nodes, size=(num_edges, 2))
print(f"Part of edges: {edges[:5, :]}")
df = pd.DataFrame(edges)
df.to_csv(edges_path, index=False, header=False)

print(f"Edges are saved into {edges_path}")

Part of edges: [[261 584]
 [582 215]
 [525 736]
 [199 130]
 [879 964]]
Edges are saved into ../../../data/dgl/ondisk_dataset_homograph\edges.csv


Generate feature data for graph

In [9]:
# Generate node feature in numpy array.
node_feat_0_path = os.path.join(base_dir, "node-feat-0.npy")
node_feat_0 = np.random.rand(num_nodes, 5)
print(f"Part of node feature [feat_0]: {node_feat_0[:3, :]}")
np.save(node_feat_0_path, node_feat_0)
print(f"Node feature [feat_0] is saved to {node_feat_0_path}\n")

# Generate another node feature in torch tensor
node_feat_1_path = os.path.join(base_dir, "node-feat-1.pt")
node_feat_1 = torch.rand(num_nodes, 5)
print(f"Part of node feature [feat_1]: {node_feat_1[:3, :]}")
torch.save(node_feat_1, node_feat_1_path)
print(f"Node feature [feat_1] is saved to {node_feat_1_path}\n")

# Generate edge feature in numpy array.
edge_feat_0_path = os.path.join(base_dir, "edge-feat-0.npy")
edge_feat_0 = np.random.rand(num_edges, 5)
print(f"Part of edge feature [feat_0]: {edge_feat_0[:3, :]}")
np.save(edge_feat_0_path, edge_feat_0)
print(f"Edge feature [feat_0] is saved to {edge_feat_0_path}\n")

# Generate another edge feature in torch tensor
edge_feat_1_path = os.path.join(base_dir, "edge-feat-1.pt")
edge_feat_1 = torch.rand(num_edges, 5)
print(f"Part of edge feature [feat_1]: {edge_feat_1[:3, :]}")
torch.save(edge_feat_1, edge_feat_1_path)
print(f"Edge feature [feat_1] is saved to {edge_feat_1_path}\n")


Part of node feature [feat_0]: [[0.82004028 0.78046455 0.0275947  0.37643646 0.32720027]
 [0.31898386 0.66563717 0.34796475 0.58852714 0.64941815]
 [0.5465205  0.21895346 0.80124164 0.18662825 0.81369575]]
Node feature [feat_0] is saved to ../../../data/dgl/ondisk_dataset_homograph\node-feat-0.npy

Part of node feature [feat_1]: tensor([[0.8605, 0.2468, 0.1715, 0.8992, 0.5508],
        [0.5529, 0.9438, 0.6789, 0.6452, 0.8538],
        [0.9630, 0.6347, 0.3732, 0.0950, 0.4641]])
Node feature [feat_1] is saved to ../../../data/dgl/ondisk_dataset_homograph\node-feat-1.pt

Part of edge feature [feat_0]: [[0.61011293 0.00360849 0.84215007 0.97483102 0.83702901]
 [0.9022446  0.88211169 0.72230691 0.14724787 0.20859767]
 [0.93742945 0.14785462 0.14806762 0.5537597  0.25670627]]
Edge feature [feat_0] is saved to ../../../data/dgl/ondisk_dataset_homograph\edge-feat-0.npy

Part of edge feature [feat_1]: tensor([[0.9157, 0.7593, 0.6878, 0.4095, 0.7023],
        [0.2242, 0.6833, 0.5608, 0.9647, 0.2

Generate tasks¶